name = input("Enter your full name:")
student_id = input("Enter your student ID:")
department = input("Enter your department:")
github_username = input("Enter your Github username:")
programming_goal = input("Enter one programming goal:")

print("\n---STUDENT CARD---")
print(f"Name : {name}")
print(f"Student ID :{student_id}")
print(f"Department :{department}")
print(f"Github Username :{github_username}")
print(f"Goal : {programming_goal}")
